// Package ovpnconf renders and validates the openvpn server config.
package ovpnconf

import (
	"cmp"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"
)

// ErrNoRedirect: split-tunnel has nothing to opt out of unless the server
// redirects all traffic. One check, shared by the CLI and the API.
var ErrNoRedirect = errors.New("server doesn't redirect all traffic; nothing to split")

// CanSplitTunnel reports whether a client may opt out of the server's redirect.
func (c Config) CanSplitTunnel() bool { return c.RedirectGW }

type Config struct {
	Proto      string   // udp|tcp
	Port       int      // 1-65535
	Subnet     string   // CIDR, e.g. 10.8.0.0/24
	Cipher     string   // from allowedCiphers
	DNS        []string // pushed resolvers
	Routes     []string // pushed routes, CIDR
	RedirectGW bool     // push redirect-gateway
	Extra      string   // raw directives, appended verbatim; unvalidated by design

	// paths (filled by the app from its data dir)
	CACert, ServerCert, ServerKey, CRL, TLSCrypt, MgmtSocket, StatusLog string
	RunAsUser, RunAsGroup                                               string // e.g. nobody/nogroup; empty = omit
}

func Default() Config {
	return Config{
		Proto: "udp", Port: 1194, Subnet: "10.8.0.0/24",
		Cipher: "AES-256-GCM", RedirectGW: true,
		RunAsUser:  cmp.Or(os.Getenv("OVCP_OPENVPN_USER"), "nobody"),
		RunAsGroup: cmp.Or(os.Getenv("OVCP_OPENVPN_GROUP"), "nogroup"),
	}
}

// Load parses a persisted config JSON blob (the store's "server_config"
// setting), falling back to defaults for anything empty or missing. raw =
// "" (never configured yet) returns plain Default().
func Load(raw string) Config {
	cfg := Default()
	if raw != "" {
		json.Unmarshal([]byte(raw), &cfg)
	}
	return cfg
}

var allowedCiphers = map[string]bool{
	"AES-256-GCM": true, "AES-128-GCM": true, "CHACHA20-POLY1305": true,
}

func (c *Config) Validate() error {
	if c.Proto != "udp" && c.Proto != "tcp" {
		return fmt.Errorf("ovpnconf: proto must be udp or tcp")
	}
	if c.Port < 1 || c.Port > 65535 {
		return fmt.Errorf("ovpnconf: port out of range")
	}
	if !allowedCiphers[c.Cipher] {
		return fmt.Errorf("ovpnconf: cipher %q not allowed", c.Cipher)
	}
	if _, _, err := net.ParseCIDR(c.Subnet); err != nil {
		return fmt.Errorf("ovpnconf: subnet: %w", err)
	}
	for _, d := range c.DNS {
		if net.ParseIP(d) == nil {
			return fmt.Errorf("ovpnconf: bad DNS ip %q", d)
		}
	}
	for _, r := range c.Routes {
		if _, _, err := net.ParseCIDR(r); err != nil {
			return fmt.Errorf("ovpnconf: route %q: %w", r, err)
		}
	}
	return nil
}

// Render emits server.conf. Assumes Validate passed.
func (c *Config) Render() []byte {
	ip, ipnet, _ := net.ParseCIDR(c.Subnet)
	mask := net.IP(ipnet.Mask).String()
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }
	w("# generated by ovcp — do not edit; changes are overwritten")
	w("proto %s", c.Proto)
	w("port %d", c.Port)
	w("dev tun")
	w("topology subnet")
	w("server %s %s", ip.Mask(ipnet.Mask), mask)
	w("ca %s", c.CACert)
	w("cert %s", c.ServerCert)
	w("key %s", c.ServerKey)
	w("crl-verify %s", c.CRL)
	w("tls-crypt %s", c.TLSCrypt)
	w("dh none") // EC only
	// DCO breaks mgmt status polling after privilege drop (dco_get_peer
	// netlink → EPERM → forced session restarts). Requires OpenVPN 2.6+.
	w("disable-dco")
	w("data-ciphers %s", c.Cipher)
	w("data-ciphers-fallback %s", c.Cipher)
	w("auth SHA256")
	w("keepalive 10 60")
	// openvpn drops to nobody after startup; persist-key/-tun let it keep
	// the tun device and key across a SIGUSR1 reconnect without re-reading
	// the root-owned files it can no longer access.
	w("persist-key")
	w("persist-tun")
	if c.RunAsUser != "" {
		w("user %s", c.RunAsUser)
		w("group %s", c.RunAsGroup)
	}
	w("management %s unix", c.MgmtSocket)
	w("status %s 10", c.StatusLog)
	w("status-version 3")
	w("verb 3")
	if c.RedirectGW {
		w(`push "redirect-gateway def1 bypass-dhcp"`)
	}
	for _, d := range c.DNS {
		w(`push "dhcp-option DNS %s"`, d)
	}
	for _, r := range c.Routes {
		rip, rnet, _ := net.ParseCIDR(r)
		w(`push "route %s %s"`, rip.Mask(rnet.Mask), net.IP(rnet.Mask))
	}
	if c.Proto == "udp" {
		w("explicit-exit-notify 1")
	}
	if extra := strings.TrimSpace(c.Extra); extra != "" {
		w("# --- custom options ---")
		w("%s", extra)
	}
	return []byte(b.String())
}

// WriteAtomic renders and installs the config via tmp+rename.
func (c *Config) WriteAtomic(path string) error {
	if err := c.Validate(); err != nil {
		return err
	}
	tmp := filepath.Join(filepath.Dir(path), ".server.conf.tmp")
	if err := os.WriteFile(tmp, c.Render(), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
