# drop-in for openvpn-server@ovcp: use ovcp-rendered config
# install to /etc/systemd/system/openvpn-server@ovcp.service.d/override.conf
[Service]
ExecStart=
ExecStart=/usr/sbin/openvpn --status %t/openvpn-server/status-%i.log --status-version 2 --suppress-timestamps --config /var/lib/ovcp/server.conf
ExecReload=/bin/kill -HUP $MAINPID
